### ISSUE TITLE
out of date/incorrect documentation examples seem blocked on new release

### ISSUE THREAD

**Issue by ThisGuyCodes** [terraform-providers/terraform-provider-null#13]
this commit:
https://github.com/terraform-providers/terraform-provider-null/commit/0f79465c0f1f70540a9283a31797e2fe29ca54c7#diff-8041bb08faeea868b9eb0935d880a960

which corrects the examples found here: https://www.terraform.io/docs/providers/null/data_source.html

appears to be blocked by a new release of this repo? And/or a submodule update of the parent website repo.

**Comment by apparentlymart** [comment]
Thanks for pointing this out, @ThisGuyCodes!

Normally the website gets updated automatically as part of a release, but indeed there has been no code release for this provider for some time and so the website was lagging behind.

We have a process for dealing with ad-hoc documentation updates without making a release, so I've done that here and the commit you mentioned is now reflected on the live website.
