### ISSUE TITLE
incompatible with Terraform v0.12

### ISSUE THREAD

**Issue by nusnewob** [terraform-providers/terraform-provider-null#31]
Hi there,

The current release of Null provider is not compatible with Terraform v0.12 release.

### Terraform Version
`Terraform v0.12.0`

### Affected Resource(s)
Null Resource and Data Source

### Terraform Configuration Files
```hcl
provider "null" {
	version = "~> 2.1"
}

resource "null_resource" "anything" {
	provisioner "local-exec" {
		command = "env"
	}
}
```

### Debug Output
```
$ terraform 0.12checklist
After analyzing this configuration and working directory, we have identified some necessary steps that we recommend you take before upgrading to Terraform v0.12:

- [ ] Upgrade provider "null" to version 2.1.2 or newer.

  No currently-installed version is compatible with Terraform 0.12. To upgrade, set the version constraint for this provider as follows and then run `terraform init`:

      version = "~> 2.1.2"

Taking these steps before upgrading to Terraform v0.12 will simplify the upgrade process by avoiding syntax errors and other compatibility problems.
```

### Expected Behavior
Terraform downloads a version 0.12 compatible release.

### Actual Behavior
```
$ terraform init
Provider "null" v1.0.0 is not compatible with Terraform 0.12.0.

Provider version 2.1.0 is the earliest compatible version. Select it with
the following version constraint:

	version = "~> 2.1"

Terraform checked all of the plugin versions matching the given constraint:
    ~> 1.0

Consult the documentation for this provider for more information on
compatibility between provider and Terraform versions.
```

Setting provider version to `init` suggested `~> 2.1` as above configuration file example resulted error,

```
$ terraform init
No provider "null" plugins meet the constraint "~> 1.0,~> 2.1".

The version constraint is derived from the "version" argument within the
provider "null" block in configuration. Child modules may also apply
provider version constraints. To view the provider versions requested by each
module in the current configuration, run "terraform providers".

To proceed, the version constraints for this provider must be relaxed by
either adjusting or removing the "version" argument in the provider blocks
throughout the configuration.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. upgrade Terraform to v0.12
1. `terraform init`

**Comment by apparentlymart** [comment]
Hi @nusnewob,

Based on the final error message you mentioned here, it sounds like you added a new version constraint for `~> 2.1` but didn't remove the existing one for `~> 1.0`, so you now have two version constraints that are conflicting with one another: you can't require both a 1.x.x release _and_ a 2.x.x release at the same time.

The `terraform providers` command may help you see where the other constraint is coming from. A child module might have its own constraint, for example. We recommend that root modules use `~>` constraints to set both a lower and upper limit on versions while any reusable child modules use only `>=` constraints to set a lower bound that includes the features they depend on, leaving the root module alone to set the upper bound.
